package org.jumbo.simpletrace.constants;

public interface Constants {
    String BASE_TEST_URL = "https://test.vkusvill.ru/api/catalog4";
    String BASE_PROD_URL = "https://mobile.vkusvill.ru/api/catalog4";
    String BASE_PREPROD_URL = "http://10.1.240.80:8081/api/catalog4";
    String BASE_TEST_URL_NOCATALOG = "https://test.vkusvill.ru/api";
    String BASE_PROD_URL_NOCATALOG = "https://mobile.vkusvill.ru/api";
    String JAEGER_URL_TEST = "http://10.0.15.41:16686/trace/";
    String FALSHTEASER = "/falseteaser/group";
    String CATEGORY = "/category";
    String SET = "/set";
    String PRODUCT = "/product";
    String SEARCH = "/search";
    String TEASERS = "/teasers";
    String PRODUCT_PROPERTIES = "/integrations/product_properties";
    String SHOPPING_LIST = "/shopping_list/product";
    String TREE_AVAILABLE = "/falseteaser/tree/available";
    String BFF_GET_SCREEN_WIDGETS = "/bff/get_screen_widgets";
    String FALSETEASER_TITLE = "FALSETEASER";
    String X_TRACE_ID = "X-Trace-Id";
    String UBER_TRACE_ID = "Uber-Trace-Id";
    String NUMBER_4 = "F324683" ;
    String NUMBER_5 = "F324819";
    String TOKEN_4 = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJjYXJkIjoiRjMyNDY4MyIsInZlcnNpb24iOjJ9.Wy_9YSiMEybVgAdLrA0IoFVw54a4g_nSWIDYaOon8rjyLPzkyJKUdZuHH3PSaA2xlY1aJfXzirpsFG2lala6h-8jsXQopBwwhF7M1hheZwskf6bcdNsYjXm760UBKC-Ot2yxzQfAO1fYMX5DZlogHvNjPDvK3kToDvOJFSVkBqk";
    String TOKEN_5 = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJjYXJkIjoiRjMyNDgxOSIsInZlcnNpb24iOjJ9.LbTs_lp8UKoV2L0IeFjlFZfQ6Icy4KYMOO0Bg5iZVT75zyx_iL-wyWkMyANvtLIyRQMpy_5hpNvP41xyUz_CIWWe1YZ4XJ4AYlkkynfV70AZYN6e4qdSGXCXboGiO5kJjQV04SfLWoc8TS8UyRXlLvHv5UrtZVXDQuaLqq8KaRA";
    String TOKEN_INT = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJHcmVlbi1UZWFtLVZrdXN2aWxsIiwiaWF0IjoxNzA2MjYxMzEwLCJleHAiOjE4OTU1NjM3MTAsImF1ZCI6Imh0dHBzOi8vdmt1c3ZpbGwucnUvIiwic3ViIjoiSW50ZWdyYXRpb24iLCJHaXZlbk5hbWUiOiJHbyBGYXRoZXIiLCJTdXJuYW1lIjoiU3VnZ2FyRGFkZHkiLCJSb2xlIjpbIkdvICIsIlByb2plY3QgQWRtaW5pc3RyYXRvciJdfQ.VdBd8T2zAfGxXuaO6zB7lSA68fhQnc_KBMsTG0XOSG8";
    String CATEGORY_ID= "50361";
    String SET_ID = "10388";
    String PRODUCT_ID = "731";
    String PRODUCT_STR_ID = "24774, 85993, 42133, 43468, 76986, 615, 46, 16055, 1744, 31137";
    String SHOPPING_LIST_ID = "3973714";
    String SHOP_ID = "3721";
    String FALSETEASER_4 = "4";
    String FALSTEASER_17 = "17";
    String FALSTEASER_18 = "18";
    String FALSTEASER_19 = "19";
    String FALSTEASER_20 = "20";
    String CATALOG_MAIN = "CatalogMain";
    String SUCCESS_COLOR_FIELD = "-fx-background-color: rgba(173, 235, 173);";
    String SUCCESS_COLOR_TEXT = "-fx-text-fill: rgba(80,200,120);";
    String ERROR_COLOR_FIELD = "-fx-background-color: rgb(247, 202, 217);";
    String ERROR_COLOR_TEXT = "-fx-text-fill: rgba(255,50,50);";
    String RESULT_BLANKS_TEXT = "Select the env and endpoint and click Apply";
    String RESULT_CURL_TEXT = "Enter curl and click Apply";
    Integer REPEATS = 20;
    String DARK = "Dark";
    String LIGHT = "Light";
    String SEARCH_QUERY = "Бананы";

}
